/* recognizeExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file a recognizer acceptExpression is definined that can recognize
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 *
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the recognizer is the token list constructed by the scanner (in scanner.c).
 * For the recognition of a token list the method of *recursive descent* is used.
 * It relies on the use of three functions for the recognition and processing of
 * terms, factors and expressions, respectively.
 * These three functions are defined with mutual recursion, corresponding with the
 * structure of the BNF grammar.
 */

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include <string.h>
#include "scanner.h"
#include "recognizeEq.h"

/* The functions acceptNumber, acceptIdentifier and acceptCharacter have as
 * (first) argument a pointer to an token list; moreover acceptCharacter has as
 * second argument a character. They check whether the first token
 * in the list is a number, an identifier or the given character, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptNumber(List *lp) {
  if (*lp != NULL && (*lp)->tt == Number) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptIdentifier(List *lp) {
  if (*lp != NULL && (*lp)->tt == Identifier) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptCharacter(List *lp, char c) {
  if (*lp != NULL && (*lp)->tt == Symbol && ((*lp)->t).symbol == c) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

/* The functions acceptFactor, acceptTerm and acceptExpression have as
 * argument a pointer to a token list. They check whether the token list
 * has an initial segment that can be recognized as factor, term or expression, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptTerm(List *lp) {
  int num, identifier, charac, power;
  num = acceptNumber(lp);
  identifier = acceptIdentifier(lp);
  charac = acceptCharacter(lp, '^');
  power = acceptNumber(lp);
  // if ((!num && !identifier && !charac && !power) || (identifier && charac && !power) || (!identifier && charac && power))
  //   return 0;
  // return 1;
	if ((num && identifier && charac && power) || (!num && identifier && charac && power) ||
		(!num && identifier && !charac && !power) || (num && !identifier && !charac && !power) || 
		(num && identifier && !charac && !power))
		return 1;
	return 0;
}

int acceptExpression(List *lp) {
  int i;
  i = acceptCharacter(lp, '-');
  if (!acceptTerm(lp)) {
    return 0;
  }
  while (acceptCharacter(lp, '+') || acceptCharacter(lp, '-')) {
    if (!acceptTerm(lp)) {
      return 0;
    }
  } /* no + or -, so we reached the end of the expression */
  return 1;
}

int acceptEquation(List *lp) {
  return (acceptExpression(lp) && acceptCharacter(lp, '=') && acceptExpression(lp));
}

/* The function findDegree finds the degree of the equation*/
int findDegree(List li) {
  int power = 1;
  while (li != NULL) {
    if (li->tt == Symbol && (li->t).symbol == '^') {
      li = li->next;
      if ((li->tt == Number) && ((li->t).number > power))
        power = (li->t).number; 
    }
    li = li->next;
  }
  return power;
}

/* The function varNum determines if the expresion has only one variable or more*/
/* Return 0 if it's only 1 variable and 1 if there are more */
int varNum(List li) {
	char *varName ;
	int flag = 0;
	while (li != NULL) {
		if (li->tt ==Identifier) {
			if (flag == 0) {
				varName = (li->t).identifier;
				flag++;
			}
			else {
				if (strcmp(varName, (li->t).identifier) != 0)
					return 1;
			}
		}
		li = li->next;
	}
	if (!flag)
		return 1;
	return 0;
}

/* The function recognizeExpressions demonstrates the recognizer. */
void recognizeEqutions() {
  char *ar;
  List tl, tl1;
  printf("give an equation: ");
  ar = readInput();
  while (ar[0] != '!') {
    tl = tokenList(ar);
    tl1 = tl;
		printList(tl);
    if (acceptEquation(&tl1) && tl1 == NULL) {
      printf("\nthis is an equation");
			if (!varNum(tl)) {
				printf(" in 1 variable of degree %d\n", findDegree(tl));
			} else if (varNum(tl)){
				printf(", but not in 1 variable\n");
			}
    } else {
      printf("this is not an equation\n");
    }
    free(ar);
    freeTokenList(tl);
    printf("\ngive an equation: ");
    ar = readInput();
  }
  free(ar);
  printf("good bye\n");
}
